# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
@user1 = User.create({ first_name: 'Valentyna', last_name: 'Gorbachenko', nickname: 'Valie', email: 'valie@codingdojo.com', password: 'password', password_confirmation: 'password' })
@user2 = User.create({ first_name: 'Sang', last_name: 'Yun', nickname: 'Sang316', email: 'sang316@gmail.com', password: 'password', password_confirmation: 'password' })
@user3 = User.create({ first_name: 'Carlos', last_name:'Chen', nickname: 'Charie', email:'charie86@gmail.com', password: 'password', password_confirmation: 'password' })
@user4 = User.create({ first_name: 'Dahye', last_name: 'Hwang', nickname: 'Grace', email: 'grace@codingdojo.com', password: 'password', password_confirmation: 'password' })
@user5 = User.create({ first_name: 'Mike', last_name: 'Lee', nickname: 'MK:)', email:'mklee@gmail.com', password: 'password', password_confirmation: 'password' })

## post means top level messages
## comment means any message which has parent message

@post1 = Message.create({ content: 'This is post 1 from user 1', user: @user1 })
@post2 = Message.create({ content: 'This is post 2 from user 4', user: @user4 })
@post3 = Message.create({ content: 'This is post 3 from user 3', user: @user3 })
@post4 = Message.create({ content: 'This is post 4 from user 3', user: @user3 })
@post5 = Message.create({ content: 'This is post 5 from user 5', user: @user5 })
@post6 = Message.create({ content: 'This is post 6 from user 2', user: @user2 })
@post7 = Message.create({ content: 'This is post 7 from user 5', user: @user5 })

@comment1 = Message.create({ content: 'This is comment 1 for post 1, from user 5', user: @user5, parent: @post1 })
@comment2 = Message.create({ content: 'This is comment 2 for post 3, from user 2', user: @user2, parent: @post3 })
@comment3 = Message.create({ content: 'This is comment 3 for post 4, from user 2', user: @user2, parent: @post4 })
@comment4 = Message.create({ content: 'This is comment 4 for post 4, from user 1', user: @user1, parent: @post4 })
@comment5 = Message.create({ content: 'This is comment 5 for post 2, from user 3', user: @user3, parent: @post2 })
@comment6 = Message.create({ content: 'This is comment 6 for post 1, from user 4', user: @user4, parent: @post1 })
@comment7 = Message.create({ content: 'This is comment 7 for post 1, from user 2', user: @user2, parent: @post1 })
@comment8 = Message.create({ content: 'This is comment 8 for post 5, from user 3', user: @user3, parent: @post5 })
@comment9 = Message.create({ content: 'This is comment 9 for post 6, from user 4', user: @user4, parent: @post6 })
@comment10 = Message.create({ content: 'This is comment 10 for post 7, from user 3', user: @user3, parent: @post7 })

@like1 = Like.create({ user: @user1, message: @post7 })
@like2 = Like.create({ user: @user1, message: @comment2 })
@like3 = Like.create({ user: @user4, message: @comment4 })
@like4 = Like.create({ user: @user2, message: @post7 })
@like5 = Like.create({ user: @user3, message: @post1 })
@like6 = Like.create({ user: @user5, message: @post2 })
@like7 = Like.create({ user: @user5, message: @post5 })
@like8 = Like.create({ user: @user5, message: @post6 })
@like9 = Like.create({ user: @user2, message: @comment1 })
@like10 = Like.create({ user: @user3, message: @comment10 })
@like11 = Like.create({ user: @user1, message: @post3 })
@like12 = Like.create({ user: @user4, message: @post4 })
@like13 = Like.create({ user: @user1, message: @post4 })
@like14 = Like.create({ user: @user2, message: @comment1 })
@like15 = Like.create({ user: @user2, message: @comment3 })
@like16 = Like.create({ user: @user4, message: @comment5 })
@like17 = Like.create({ user: @user3, message: @comment5 })
@like18 = Like.create({ user: @user4, message: @comment1 })
@like19 = Like.create({ user: @user2, message: @comment6 })
@like20 = Like.create({ user: @user2, message: @comment8 })
@like21 = Like.create({ user: @user3, message: @comment8 })
@like22 = Like.create({ user: @user1, message: @post6 })
@like23 = Like.create({ user: @user5, message: @post6 })
@like24 = Like.create({ user: @user4, message: @comment10 })
@like25 = Like.create({ user: @user5, message: @comment1 })
@like26 = Like.create({ user: @user5, message: @comment9 })
@like27 = Like.create({ user: @user2, message: @comment9 })
@like28 = Like.create({ user: @user4, message: @comment9 })
@like29 = Like.create({ user: @user3, message: @post2 })
@like30 = Like.create({ user: @user4, message: @post4 })